n=int(input("Enter the number of rows:"))
for i in range(1,n+1):  #this for_loop is use to print rows....
    for j in range(1,n+1): #this for_loop is use to print cols...
        print(n+1-i,end=" ")
    print()   #this print() use to print new line
